Add missing header for C++23
Add the <functional> header to resolve C++23 build errors because
C++23 removed transitive includes so you have to add the headers
directly.

Error:
external/v4l2_codec2/tests/c2_e2e_test/jni/mediacodec_encoder.h:26:38:
error: no template named 'function' in namespace 'std'
   26 |     using EncodeInputBufferCb = std::function<void(uint64_t /*
time_us */)>;
external/v4l2_codec2/tests/c2_e2e_test/jni/mediacodec_encoder.h:29:18:
error: no template named 'function' in namespace 'std'
   29 |             std::function<void(const uint8_t* /* data */, const
AMediaCodecBufferInfo& /* info */)>;
external/v4l2_codec2/tests/c2_e2e_test/jni/mediacodec_decoder.h:38:38:
error: no template named 'function' in namespace 'std'
   38 |     using OutputBufferReadyCb = std::function<void(

Generated by Gemini.

Flag: EXEMPT PURE_REFACTOR
Bug: 429048222
Test: m libcodectest
Change-Id: I5da089b7664bbf54f5143131018c02eb6049776c